/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package tutorial;

import java.util.HashMap;
import java.util.Map;

public class Constants {

    /**
     * Thrift also lets you define constants for use across languages. Complex
     * types and structs are specified using JSON notation.
     */
    public static final int INT32CONSTANT = 9853;

    public static final Map<String, String> MAPCONSTANT = new HashMap<String, String>();

    static {
        MAPCONSTANT.put("hello", "world");
        MAPCONSTANT.put("goodnight", "moon");
    }

}
